#!/usr/local/bin/bash

#env
#exit

set -u
set -e

ruby=$1
shift
PATH=$HOME/.rvm/bin:$PATH

if [ -s $HOME/.rvm/scripts/rvm ]; then
#	. $HOME/.rvm/scripts/rvm
#	echo RVM loaded
	if [ -s $HOME/.rvm/environments/ruby-${ruby} ]; then
		. $HOME/.rvm/environments/ruby-${ruby}
#		echo Ruby initialized
	fi
fi

#echo $HOME

#rvm use $ruby

command=$1
shift

$command $*
exit $?
