#!/usr/local/bin/bash

set -u
set -e

ruby=$1
shift
export SHELL=/usr/local/bin/bash
PATH=$HOME/.rvm/bin:$PATH

if [ -s $HOME/.rvm/scripts/rvm ]; then
	. $HOME/.rvm/scripts/rvm
	echo RVM loaded
	if [ -d $HOME/.rvm/environments/ruby-${ruby} ]; then
		. $HOME/.rvm/environments/ruby-${ruby}
		echo Ruby initialized
	fi
fi

echo $HOME

rvm use $ruby

command=$1
shift

$command $*
exit $?